import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  knowledgeHubSidebar: [
    'learning-roadmap',
    'index',
    'linux-internals/index',
    'openbmc-architecture/index',
    'yocto/index',
    'docker/index',
    'firmware-debugging/index',
  ],
  linuxInternalsSidebar: [{type: 'autogenerated', dirName: 'linux-internals'}],
  openbmcArchitectureSidebar: [
    {type: 'autogenerated', dirName: 'openbmc-architecture'},
  ],
  yoctoSidebar: [{type: 'autogenerated', dirName: 'yocto'}],
  dockerSidebar: [{type: 'autogenerated', dirName: 'docker'}],
  firmwareDebuggingSidebar: [
    {type: 'autogenerated', dirName: 'firmware-debugging'},
  ],
};

export default sidebars;
